# Schema for the configuration files of the Migrate city module.
migrate_city.settings:
  type: config_object
  label: 'Migrate city settings'
  mapping:
    example:
      type: string
      label: 'Example'
